FROM verificarlo-ubuntu18
RUN apt-get update
RUN apt install -y python3-dev python3-pip git wget unzip &&\
    pip3 install -U --user six numpy wheel setuptools mock &&\
    pip3 install -U --user keras_applications==1.0.6 --no-deps &&\
    pip3 install -U --user keras_preprocessing==1.0.5 --no-deps

RUN wget https://github.com/bazelbuild/bazel/releases/download/0.26.1/bazel-0.26.1-installer-linux-x86_64.sh &&\
    chmod +x bazel-0.26.1-installer-linux-x86_64.sh &&\
    ./bazel-0.26.1-installer-linux-x86_64.sh

RUN git clone https://github.com/tensorflow/tensorflow.git

# Setting compilers and linkers to use verificarlo
ENV CC "verificarlo"
ENV CXX "verificarlo"
ENV FC "verificarlo"
ENV LD "verificarlo"
ENV LDSHARED "verificarlo -shared"
ENV VFC_BACKENDS "libinterflop_ieee.so"
ENV PYTHON_BIN_PATH=/usr/bin/python3 
# clang4.0 depends on Python2.7 so we can't just remove python2.7

# This should be fixed in verificarlo's container
RUN apt purge -y llvm-6.0 libllvm6.0 llvm-6.0-runtime clang
RUN apt install -y clang-4.0 && ln -s /usr/bin/clang-4.0 /usr/bin/clang

# Move pip3 install up
RUN cd tensorflow && git checkout v2.0.0 && ./configure &&\
    pip3 install future &&  bazel build //tensorflow/tools/pip_package:build_pip_package

RUN cd tensorflow && ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg


