FROM ubuntu:latest
RUN apt-get update
ENV DEBIAN_FRONTEND=noninteractive 
RUN apt install -y bash ca-certificates make git libmpfr-dev \
    clang llvm-4.0 llvm-4.0-dev  gcc g++ autoconf automake libedit-dev libtool\
    libz-dev python3 python3-numpy python3-matplotlib binutils vim
ENV LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/8:/usr/lib/llvm-6.0/lib:$LIBRARY_PATH
RUN git clone https://github.com/verificarlo/verificarlo.git && \
    cd verificarlo &&\ 
    ./autogen.sh &&\
    ./configure --with-llvm=/usr/lib/llvm-4.0/bin/ CC=gcc-7 CXX=g++-7 --without-dragonegg &&\
    make && make install

